baseURL = "https://braindump.jethro.dev/"
languageCode = "en-us"
title = "Jethro's Braindump"
theme = "cortex"

[params]
attributions = "Icon by Laymik from The Noun Project. Website Built with ♥ with Org-mode, Hugo, and Netlify."
email = "jethrokuan95@gmail.com"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4